### ISSUE TITLE
Permission to use your graphic

### ISSUE THREAD

**Issue by noisy** [lcolladotor/lcolladotor.github.com#3]
Hi,

I found in google image search your repository, after typing "Let's Code'. 

In document https://github.com/lcolladotor/lcolladotor.github.com/blob/master/_posts/2015-07-07-rmarkdown.md you have very [nice graphic](https://camo.githubusercontent.com/faad40ccaf64fad209fe551e5a273cc661cd7239/687474703a2f2f64676463352e6469676974616c67616d65736c6561726e696e672e6f72672f646764635f3574682f77702d636f6e74656e742f75706c6f6164732f6c632e706e67). I want to ask you, whether you are the author of it, and can I use it for my own productions, which actually has similar name: https://www.youtube.com/playlist?list=PLVnxlFtdce51NiiIzjhQw27Q7NM8T7ikB.

Best Regards,
Krzysztof

**Comment by lcolladotor** [comment]
Hi Krzysztof,

I didn't make the graphic. I found it online at http://dgdc5.digitalgameslearning.org/dgdc_5th/wp-content/uploads/lc.png, which you can see in the source file.

Best,
Leo
