### ISSUE TITLE
broken RSS feed

### ISSUE THREAD

**Issue by maelle** [lcolladotor/lcolladotor.github.com#4]
:wave: @lcolladotor, congrats on the new job!

It seems your RSS feed is broken see https://twitter.com/rweekly_live/status/1308114306555351043 it contains relative links.

I don't see the source of the layouts in this repo so I'm afraid I can't help.

**Comment by lcolladotor** [comment]
Hm... http://lcolladotor.github.io/categories/rstats/index.xml seems dead =( I'll check https://github.com/lcolladotor/lcolladotorsource/blob/master/layouts/_default/rss.xml then. Thanks for the heads up Maëlle!

**Comment by lcolladotor** [comment]
I just fixed it by taking a peak at one of your repos =) Thanks again Maëlle!

**Comment by maelle** [comment]
ahahah then I feel less bad about not directly helping!! awesome, well done!

**Comment by lcolladotor** [comment]
Hehe no worries. I remember that in the past I had to edit the RSS template because using a non-relative baseURL lead to some issues. But well, that was in 2018 and anyways, this way I have to less manual updating whenever I update the hugo-academic git submodule ^^
